### ISSUE TITLE
ログイン機能の動作確認をすることができない

### ISSUE THREAD

**Issue by Seiya830** [Seiya830/mavs-task#1]
## 概要
環境構築を終えて、メモアプリのトップページまで表示することができました。
あらかじめ用意していただいたメールアドレス、パスワードを入力すると404エラーが表示され、ログインすることができません。

## 実際の動作
https://github.com/Seiya830/mavs-task/assets/102199562/be36c1fd-6c66-47e3-839f-2ccfbdf56f64

## エラーコード
`Failed to load resource: the server responded with a status of 404 (Page not found: /auth/signin)`

## ターミナルでの表示
`mavs-task      | [Vue Router warn]: No match found for location with path "/auth/signin"`

Vue Routerが指定されたパスに一致するルートを見つけられない場合に表示されるということまでは理解することができました。

また、`docker compose up --build`
でDockerを起動した際のターミナルでの表示にAPIに関してのエラーが出ているのが原因ではないかと考えています。
<img width="758" alt="スクリーンショット 2023-09-24 14 43 54" src="https://github.com/Seiya830/mavs-task/assets/102199562/b926b889-ecef-4be4-b10f-c54907de7293">

試すべきこと、解決方法等をを教えていただけると幸いです...

**Comment by taro-dev** [comment]
@Seiya830 
確かにAPIが起動していないように見えますね、、

バックエンド起動時に
```
mavs-task-api  | API Server Start
```
と表示されていますか？？

もしなければバックエンドの起動自体に失敗しています！

もしその場合は再度下記を試してみていただければと思います！
https://github.com/mavericks-inc/mavs-task#%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

frontend / backendそれぞれのフォルダ内に`node_modules`が存在してればOKです！

**Comment by Seiya830** [comment]
@taro-dev 
ご対応ありがとうございます！
```
mavs-task-api  | API Server Start
```
の表示が見つからなかった為、起動に失敗しているようです...!
再度パッケージインストールの手順から行いましたが、解消できませんでした。。

frontend / backendそれぞれのフォルダ内に`node_modules`の存在は確認できました！

<img width="1680" alt="スクリーンショット 2023-09-26 6 57 22" src="https://github.com/Seiya830/mavs-task/assets/102199562/802479a7-7ede-43dc-8661-e94ed625970e">


Dockerを確認するとAPIの項目のみ動作していませんでした。


<img width="1680" alt="スクリーンショット 2023-09-26 6 57 47" src="https://github.com/Seiya830/mavs-task/assets/102199562/df2d51f0-a6b2-46c0-a24a-03a73914c92b">

Dockerコンテナ内で`nodemon`が見つからないために発生しているようなのでもう少し調べてみたいと思います！

**Comment by taro-dev** [comment]
@Seiya830 
ありがとうございます！
`nodemon`は`package.json`に入っており、`yarn install`で入るはずなので、
インストールされていないのでは・・と思っていました！

`backend/node_modules`の中に`nodemon`は入っていそうでしょうか！
![image](https://github.com/Seiya830/mavs-task/assets/40144271/9ad1d324-3c77-4ff7-906d-42b2d0755422)

**Comment by p-t-a-p-1** [comment]
@Seiya830 
もしかするとyarnのバージョンが1系以外の場合は動かないかもしれません..！！

```
yarn -v
```
でバージョン確認していただきたいです！
`1.22.19`の場合は正常に動作するはずです..！


※追記
参考までに、正常に動作する際のターミナル画面を添付いたします！
<img width="1672" alt="image" src="https://github.com/Seiya830/mavs-task/assets/51960141/92ff86f4-edaa-4216-b2c5-c8e96172adf5">

**Comment by Seiya830** [comment]
@taro-dev 
確認ありがとうございます！
チェックしたところ、`nodemon`が入っていることが確認できました！
<img width="1680" alt="スクリーンショット 2023-09-26 9 46 40" src="https://github.com/Seiya830/mavs-task/assets/102199562/2801cd65-d439-4ccb-be83-36cb7bfbb012">

**Comment by Seiya830** [comment]
@p-t-a-p-1
ご連絡ありがとうございます！
yarnのバージョンを確認したところ、`1.22.19`でした...!
<img width="838" alt="スクリーンショット 2023-09-26 11 42 33" src="https://github.com/Seiya830/mavs-task/assets/102199562/827e1b16-9972-44db-ab0d-3114b237554f">

Dockerを再度ビルドした際のターミナル画面を添付します！
<img width="1680" alt="スクリーンショット 2023-09-26 11 47 53" src="https://github.com/Seiya830/mavs-task/assets/102199562/80ca28a1-0665-4062-b788-66f606a8adb8">
<img width="1680" alt="スクリーンショット 2023-09-26 11 48 09" src="https://github.com/Seiya830/mavs-task/assets/102199562/76df5a70-18a8-4e7b-a3e4-fc4dcf6bf25f">

各バージョンは以下のようになっています！
<img width="829" alt="スクリーンショット 2023-09-26 11 56 30" src="https://github.com/Seiya830/mavs-task/assets/102199562/2893773d-46f7-4a14-8b01-8d31b086429c">

他に確認すべき項目等はありますでしょうか...?

**Comment by p-t-a-p-1** [comment]
@Seiya830 
ご確認いただきありがとうございます！
すみません！`frontend/.env`の内容を以下のようにしていただきたいです！

```
NUXT_PUBLIC_API_BASE_URL=http://localhost:3001
```

**Comment by Seiya830** [comment]
@p-t-a-p-1 
ありがとうございます！
`frontend/.env`の内容を
```
API_BASE_URL=http://localhost:3001
```
から
```
NUXT_PUBLIC_API_BASE_URL=http://localhost:3001
```
へ変更しました！
その後再度Dockerを起動しましたが、APIが起動せず先程と同じターミナル画面になってしまいます...

**Comment by p-t-a-p-1** [comment]
@Seiya830 

一旦dockerコンテナ・イメージ周りを初期化していただきたいです！
以下のコマンドを実行お願いします
```
docker system prune -a -f --volumes ; docker rmi $(docker images -a -q) ; docker volume rm -f $(docker volume ls -q)
```

再度 `docker compose up` していただきたいです！

**Comment by Seiya830** [comment]
@p-t-a-p-1 @taro-dev 
初期化後に動作確認を行ったところ、無事ログイン機能を確認することができました！

動作確認後のターミナル画面を添付します！
<img width="1680" alt="スクリーンショット 2023-09-27 7 29 24" src="https://github.com/Seiya830/mavs-task/assets/102199562/490377ef-4757-48ec-b775-c74d19f49500">

こちらキャプチャになります

https://github.com/Seiya830/mavs-task/assets/102199562/a45ad606-ecf1-4bf2-9d6a-221984d06cee

Docker周りで何らかの不具合が起きていたんですね。。
Dockerやディレクトリ構成について改めて調べて学びになりました！
助けていただき本当にありがとうございます...!
