### ISSUE TITLE
Nuxt3 における TypeScript の型関連エラーについてのご相談

### ISSUE THREAD

**Issue by Seiya830** [Seiya830/mavs-task#13]
Nuxt3でメモの一覧を表示する機能を実装している最中に、TypeScriptの型関連のエラーが表示されました。
具体的には、`memos`というref変数を用いてAPIから取得したデータを格納しようとしているのですが、以下のエラーメッセージが出てしまいます...
```
型 'Ref<unknown>' には 型 'never[]' からの次のプロパティがありません: length, pop, push, concat、35 など。ts(2740)
```
こちら関して、試行錯誤を行ったのですが、正確な原因と解決方法がわからない状態です。
もし何かアドバイスや解決方法をご存知でしたら、教えていただけますでしょうか...？

お手数かけますがよろしくお願いいたします...！

以下に現段階での実装中の関連ファイルを添付いたします。

15行目の`memos.value = data;`の部分でエラーが発生しています。
frontend/src/pages/MemoList.vue
https://github.com/Seiya830/mavs-task/blob/14c2cd0ee1b561de36ce6633ede57d084914295b/frontend/src/pages/MemoList.vue

backend/src/services/articles/ArticleService.js
https://github.com/Seiya830/mavs-task/blob/14c2cd0ee1b561de36ce6633ede57d084914295b/backend/src/services/articles/ArticleService.js

backend/src/routes/articles/articles.router.js
https://github.com/Seiya830/mavs-task/blob/14c2cd0ee1b561de36ce6633ede57d084914295b/backend/src/routes/articles/articles.router.js

**Comment by p-t-a-p-1** [comment]
@Seiya830 
リポジトリクローンして上記のエラー再現できました！

pages/MemoList.vueのL8、
```
// メモのデータリストを格納するためのリアクティブ変数
const memos = ref([]);
```
空配列`[]`をリアクティブな変数として定義しているため、
never型という値を持たない型として定義されてしまっているようです。
never型のリアクティブ変数には何も代入できないため、エラーが表示されています。

解決するには、refの型を明示的に定義する必要あります！
```
intereface Memo {
  ...
}

const memos = ref<Memo[] | null>([])
```
また、useFetchのレスポンスで`data`を定義していましたが、
リアクティブな値のため、`data.value`を`memos.value`に代入する必要あります..！

※ こちらの記事が参考になりそうです
https://reffect.co.jp/vue/vue3-composition/#fetch-%E9%96%A2%E6%95%B0%E3%81%AE%E5%9E%8B%E8%A8%AD%E5%AE%9A

**Comment by Seiya830** [comment]
@p-t-a-p-1 
回答ありがとうございます！
型情報を定義したところ、無事にエラーを解決することができました！!

APIのメモ一覧取得の処理方法の書き方も変更しました！

こちら修正後のコードになります！
frontend/src/pages/MemoList.vue
https://github.com/Seiya830/mavs-task/blob/122011dff4f4b5313d028af8daae6dde656cc68f/frontend/src/pages/MemoList.vue
