### ISSUE TITLE
PostgreSQLへ接続テストを行いたい

### ISSUE THREAD

**Issue by Seiya830** [Seiya830/mavs-task#4]
メモ機能のCRUD操作実装前にDBとの接続テストをする必要があると思い、接続確認を行いたいのですが実行方法がわからず手が止まってしまいました...

`backend/src/models/articles.js`のファイルにメモに関してのテーブル内容があるという理解はできたのですが実際にDBの方へ追加する方法がわかりません..

新たにテストデータ、テーブルを追加する方法を教えていただきたいです...！

**Comment by sho-mavs** [comment]
こちらについて、簡単にいうと
「プログラム上(backend)からテストデータを追加する方法を知りたい」
という内容であってますでしょうか…！

---

上記の内容を前提とした話を以下に記載します！
（上記が間違っている場合は、その旨を教えていただければと思います）

ご認識いただいているかと思いますが、DBとしてはPostgreSQLを使用していますが、
それをプログラム上で操作するNode.jsのライブラリとして「Sequelize」というのを使用しています。
Sequelizeの操作方法に則ってテストデータの登録ができるようになるための、簡易手順とその概要を記載します！
こちらをお試しいただければ、DBのデータ登録が一旦はできるようになるかと思います…！

---

【手順】
1. フロント側にAPI実行用の簡易的なボタンを配置
2. テストデータ登録用APIを用意する（簡易的でOK）
3. Sequelize操作でテストデータを登録する（固定値でOK）

---

【それぞれの概要】
🔸 1について
サインイン(frontend/src/pages/signin.vue)を参考にしていただければ作れるかと思います！
テスト的に試す分には、リクエストパラメータは特に必要がないAPIがあればOKです！

🔸 2について
こちらはバックエンド側に必要なリソースを用意する話です！
サインイン(backend/src/routes/auth/auth.router.js)を参考にすれば作れるかと思います！

🔸 3について
**ここが本題となります！**
以下に参考サイトも共有しますので、ご確認いただいて試してみましょう！
とりあえずは固定値とかをデータ登録して、pgAdminでそのデータが登録されていることが確認できればOKです！

【Sequelizeの操作方法の参考サイト】
https://blog.katsubemakito.net/nodejs/mysql-sequelize1
https://qiita.com/ksh-fthr/items/7bc66911fd5c7506deeb#create--insert-
https://blog.capilano-fw.com/?p=5582#i-4

**Comment by Seiya830** [comment]
回答ありがとうございます！
手順2まで実装することがおそらくできたのですが、Sequelizeの操作方法がわからず詰まってしまいました...

現在メモの新規登録機能を実装中なのですが、
新たにテーブルを作成して、テストデータの登録を試みていたのですが、すでにarticleのテーブルが存在するため新規で作る必要はなかったのでは...?と考えています。

既存のarticleテーブルにデータを追加する方法を教えていただきたいです！

現在実装途中の下記の2つのファイルを添付します。
https://github.com/Seiya830/mavs-task/blob/c694fbc226a98de16cc69338fbf331b531193e9c/backend/src/routes/articles/articles.router.js

https://github.com/Seiya830/mavs-task/blob/c694fbc226a98de16cc69338fbf331b531193e9c/frontend/src/pages/MemoInput.vue

**Comment by sho-mavs** [comment]
お試しいただいてありがとうございます！

---

> 現在メモの新規登録機能を実装中なのですが、
> 新たにテーブルを作成して、テストデータの登録を試みていたのですが、すでにarticleのテーブルが存在するため新規で作る必要はなかったのでは...?と考えています。

こちらに関してはおっしゃる通りと思います！
Docker起動時に以下のファイルを実行しているので、その際にarticleテーブルも作られているかと思いますね！
`postgres/initdb/init.sql`

なので、自前で新規にテーブル作成とかは考えなくて良いはずです！

---

> 既存のarticleテーブルにデータを追加する方法を教えていただきたいです！

添付いただいたファイルを拝見しました。
`articles.router.js`の方ですが、`createMemo`というメソッドは、Sequelize側で用意されているメソッドではないので、動かないと思います！
以前に連携させていただいた参考サイトはご確認いただいているかと思いますが、
用意されているのは`create`というメソッドなので、そちらで試してみましょう！
そしてDBのカラム名と相違があるとデータが入れられないと思うので、以下のようにマッピングが必要かと思われます！

例） ↓動作確認していないのでお試しもお願いします…！
 ```
   const newMemo = await db.Articles.create({ ← createMemoからcreateに変更
      title,
      content: body, ← マッピングはこれ
    });
```

あと、`postgres/initdb/init.sql`をご確認いただきたいです！
create table文があるかと思いますが、
`title`、`content`、`author_id`カラムは必須項目(NOT NULL)なので、データを入れる必要があります！
`author_id`もデータ登録するために必要なのでお願いします！

**Comment by Seiya830** [comment]
確認させていただきました！
ありがとうございます！

`postgres/initdb/init.sql`の内容を見落としていました、、

以下のように2つのファイルを修正したのですが、
https://github.com/Seiya830/mavs-task/blob/1e3a50ab8eeb74315d33d5b85189135182aae49e/backend/src/routes/articles/articles.router.js

https://github.com/Seiya830/mavs-task/blob/1e3a50ab8eeb74315d33d5b85189135182aae49e/frontend/src/pages/MemoInput.vue

`MemoInput.vue:15     POST http://localhost:3000/add 404 (Page not found: /add)`
404エラーが出てしまいます。
ルーティングに関して他に設定すべき箇所はありますでしょうか...?

**Comment by sho-mavs** [comment]
ご確認ありがとうございます！

上記の内容を確認しました！
ルーティングの設定が上手くできていなさそうですので、以下2点のヒントをお伝えします！

1. `MemoInput.vue:15     POST http://localhost:3000/add 404 (Page not found: /add)`について
→3000ポートの/addに対してAPIを投げたけど、それが見つからない(404 Not Found)と言ってます！
　バックエンド側は3001ポートで動いているので、バックエンドに到達できていない（＝投げる先の誤り）ということが分かります！

3. 正常に動いているサインイン機能と見比べる
→サインイン(signin.vue)はバックエンドに到達してAPI実行ができていると思います！
　API実行部分において、今回作成いただいた`MemoInput.vue`と見比べて何が違うか確認してみましょう！
　その違いが分かれば、前進できるかと思います！！

**Comment by Seiya830** [comment]
`singin.vue`やNuxt3公式ドキュメントを参考に進めたところ、無事API実行することができ、フロント側からDBへデータを追加することができました！！

`useFetch`の使い方や`apiBaseUrl`を使用すること、DBのカラム名チェックが解決の鍵となりました！

数日に渡り助けていただき本当にありがとうございます！
